name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib
          pip3 install west
      - name: Build Left
        run: |
          west init -l config
          west update
          west build -d build/left -b nice_nano_v2 -- -DSHIELD=keyball39_left
      - name: Build Right
        run: |
          west build -d build/right -b nice_nano_v2 -- -DSHIELD=keyball39_right
      - name: Build Settings Reset
        run: |
          west build -d build/settings_reset -b nice_nano_v2 -- -DSHIELD=settings_reset
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
            build/settings_reset/zephyr/zmk.uf2