name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    env:
      RUNNER_TOOL_CACHE: /opt/hostedtoolcache
      RUNNER_TEMP: /tmp
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
          cache: 'pip'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-multilib
          pip3 install --user west
      - name: Initialize ZMK
        run: |
          west init -l config
          west update
          west zephyr-export
      - name: Build Left
        run: |
          cd config
          west build -d build/left -b nice_nano_v2 -- -DSHIELD=keyball39_left
      - name: Build Right
        run: |
          cd config
          west build -d build/right -b nice_nano_v2 -- -DSHIELD=keyball39_right
      - name: Build Settings Reset
        run: |
          cd config
          west build -d build/settings_reset -b nice_nano_v2 -- -DSHIELD=settings_reset
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            config/build/left/zephyr/zmk.uf2
            config/build/right/zephyr/zmk.uf2
            config/build/settings_reset/zephyr/zmk.uf2